version: '2'

services:
  pipeline_image:
    build: ./Image
    image: pipeline/image
    container_name: pipeline_image

  pipeline_image_yum:
    build: 
      context: ./Image
      dockerfile: Dockerfile.yum
    image: pipeline/image_yum
    container_name: pipeline_image_yum

  pipeline_image_microyum:
    build:
       context: ./Image
       dockerfile: Dockerfile.microyum  
    image: pipeline/image_microyum
    container_name: pipeline_image_microyum
    
  pipeline_input:
    build: ./Input
    image: pipeline/input
    container_name: pipeline_input
    ports:
      - 8888:8888
    depends_on:
      - pipeline_display
      - pipeline_image

  pipeline_display:
    build: ./Display
    image: pipeline/display
    container_name: pipeline_display
    ports:
      - 8080:3000
      - 8081:3001
    volumes:
      - ./Display/angular2:/angular2
    depends_on:
      - pipeline_image

  pipeline_queue:
    build: ./Queue
    image: pipeline/queue
    container_name: pipeline_queue
    hostname: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    ports:
      - "9092:9092"
      - "2181:2181"
    depends_on:
      - pipeline_input
      - pipeline_display
      - pipeline_processing
      - pipeline_image
      
  pipeline_processing:
    build: ./Processing
    image: pipeline/processing
    container_name: pipeline_processing
    depends_on:
      - pipeline_display
      - pipeline_image
      
  pipeline_output:
    build: ./Output
    image: pipeline/output
    container_name: pipeline_output
    depends_on:
      - pipeline_display
      - pipeline_image