version: '2'

services:
  pipeline_image_microyum:
    build: 
      context: ./Image
      dockerfile: Dockerfile.microyum
    image: pipeline/image_microyum
    container_name: pipeline_image_microyum
    
  pipeline_input:
    build:
      context: ./Input
      dockerfile: Dockerfile.microyum
    image: pipeline/input
    container_name: pipeline_input
    ports:
      - 8888:8888
    depends_on:
      - pipeline_display
      - pipeline_image_microyum

  pipeline_display:
    build:
      context: ./Display
      dockerfile: Dockerfile.microyum
    image: pipeline/display
    container_name: pipeline_display
    ports:
      - 8080:3000
      - 8081:3001
    volumes:
      - ./Display/angular2:/angular2
    depends_on:
      - pipeline_image_microyum

  pipeline_queue:
    build:
      context: ./Queue
      dockerfile: Dockerfile.microyum
    image: pipeline/queue
    container_name: pipeline_queue
    hostname: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    ports:
      - "9092:9092"
      - "2181:2181"
    depends_on:
      - pipeline_input
      - pipeline_display
      - pipeline_processing
      - pipeline_image_microyum
      
  pipeline_processing:
    build:
      context: ./Processing
      dockerfile: Dockerfile.microyum
    image: pipeline/processing
    container_name: pipeline_processing
    depends_on:
      - pipeline_display
      - pipeline_image_microyum
      
  pipeline_output:
    build:
      context: ./Output
      dockerfile: Dockerfile.microyum
    image: pipeline/output
    container_name: pipeline_output
    depends_on:
      - pipeline_display
      - pipeline_image_microyum